FROM node:10.15-alpine
MAINTAINER Duc Thanh Nguyen (ng.duc.tahn@gmail.com)

# Set environment
ENV NODE_ENV development

# Select Working Directory
WORKDIR /uwcourse-taskrunner

# Copy the app folder to the Working Directory
ADD ./taskrunner /uwcourse-taskrunner
COPY ./server/models /uwcourse-taskrunner/models
COPY ./utils /uwcourse-taskrunner/utils

# Create an empty data folder to store database state
# This avoid having to check if the folder exists using node.js filesystem
RUN mkdir -p /uwcourse-taskrunner/uwopendata/data

# Install all node packages
RUN npm i

# Start the API
CMD ["node", "start.js"]
