FROM node:10-alpine
MAINTAINER Duc Thanh Nguyen (ng.duc.tahn@gmail.com)

# Expose port 5000
EXPOSE 5000

# Install python to compile argon2
RUN apk add --update \
    python \
    python-dev \
    py-pip \
    build-base \
  && pip install virtualenv \
  && rm -rf /var/cache/apk/*

# Install some node packages
RUN npm i -g node-gyp

# Set environment
ENV NODE_ENV dev

# Select Working Directory
WORKDIR /uwcourse-server

# Copy package.json
COPY ./server/package.json /uwcourse-server/package.json

# Install all node packages
RUN npm i

# Copy the app folder to the Working Directory
COPY ./server /uwcourse-server

# Remove symlinks
RUN rm -rf models utils

# Copy the original symlink targets
COPY ./models /uwcourse-server/models
COPY ./utils /uwcourse-server/utils

# Start the API
CMD ["node", "server.js"]
