FROM ruby:2.5-alpine
MAINTAINER Duc Thanh Nguyen (ng.duc.tahn@gmail.com)

WORKDIR /app

COPY ./doc/Gemfile /app/Gemfile

RUN apk add --update nodejs g++ make
RUN gem install nokogiri
RUN bundle install

WORKDIR /app/doc

EXPOSE 4567

CMD ["bundle", "exec", "middleman", "server", "--watcher-force-polling"]
